import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))

MONGODB_DATABASE = os.getenv("MONGODB_DATABASE")
MONGODB_PORT = os.getenv("MONGODB_PORT")
MONGODB_PASSWORD = os.getenv("MONGODB_PASSWORD")
MONGODB_USERNAME = os.getenv("MONGODB_USERNAME")
MONGODB_URI = f"mongodb://{MONGODB_USERNAME}:{MONGODB_PASSWORD}@mongodb:{MONGODB_PORT}/{MONGODB_DATABASE}?authSource=admin"

API_DND5E = os.getenv("API_DND5E")

MONGODB_COLLECTION_ITEMS = "items"
MONGODB_COLLECTION_MONSTERS = "monsters"
MONGODB_COLLECTION_SPELLS = "spells"
MONGODB_COLLECTION_BACKGROUNDS = "backgrounds"