### Variables base
@host = http://localhost:8000
@api_token_hash = 32e469f398b2dd6e89892d33012ae447e046070c18c9f6c5f1a2430a039e5db7

### Login previo
# @name login
POST {{host}}/auth/login
Content-Type: application/json
X-API-Token: {{api_token_hash}}

{
  "username": "Oraxiel",
  "password": "admin"
}

### GET ALL MONSTERS (solo X-API-Token)
GET {{host}}/monsters/
Content-Type: application/json
X-API-Token: {{api_token_hash}}


### GET SPECIFIC MONSTER (solo X-API-Token)
GET {{host}}/monsters/archmage
Content-Type: application/json
X-API-Token: {{api_token_hash}}


### GET ANOTHER MONSTER (solo X-API-Token)
GET {{host}}/monsters/aboleth
Content-Type: application/json
X-API-Token: {{api_token_hash}}


### CREATE NEW MONSTER (requiere X-API-Token + Authorization)
POST {{host}}/monsters/
Content-Type: application/json
X-API-Token: {{api_token_hash}}
Authorization: Bearer {{login.response.body.$.access_token}}

{
  "index": "test-monster",
  "name": "Test Monster",
  "desc": "A test monster for API validation",
  "size": "Medium",
  "type": "humanoid",
  "alignment": "neutral",
  "armor_class": [
    {
      "type": "natural",
      "value": 15
    }
  ],
  "hit_points": 45,
  "hit_dice": "7d8+14",
  "hit_points_roll": "7d8+14",
  "speed": {
    "walk": "30 ft."
  },
  "strength": 14,
  "dexterity": 16,
  "constitution": 15,
  "intelligence": 12,
  "wisdom": 13,
  "charisma": 10,
  "proficiencies": [
    {
      "value": 2,
      "proficiency": {
        "index": "skill-stealth",
        "name": "Skill: Stealth",
        "url": "https://www.dnd5eapi.co/api/2014/proficiencies/skill-stealth"
      }
    }
  ],
  "damage_vulnerabilities": [],
  "damage_resistances": [],
  "damage_immunities": [],
  "condition_immunities": [],
  "senses": {
    "passive_perception": 11,
    "darkvision": "60 ft."
  },
  "languages": "Common",
  "challenge_rating": 3,
  "proficiency_bonus": 2,
  "xp": 700,
  "url": "/api/2014/monsters/test-monster"
}


### UPDATE MONSTER (requiere X-API-Token + Authorization)
PUT {{host}}/monsters/test-monster
Content-Type: application/json
X-API-Token: {{api_token_hash}}
Authorization: Bearer {{login.response.body.$.access_token}}

{
  "index": "test-monster",
  "name": "Test Monster Updated",
  "desc": "An updated test monster for API validation",
  "size": "Medium",
  "type": "humanoid",
  "alignment": "neutral",
  "armor_class": [
    {
      "type": "natural",
      "value": 16
    }
  ],
  "hit_points": 50,
  "hit_dice": "7d8+14",
  "hit_points_roll": "7d8+14",
  "speed": {
    "walk": "30 ft."
  },
  "strength": 15,
  "dexterity": 17,
  "constitution": 15,
  "intelligence": 12,
  "wisdom": 13,
  "charisma": 10,
  "proficiencies": [
    {
      "value": 3,
      "proficiency": {
        "index": "skill-stealth",
        "name": "Skill: Stealth",
        "url": "https://www.dnd5eapi.co/api/2014/proficiencies/skill-stealth"
      }
    }
  ],
  "damage_vulnerabilities": [],
  "damage_resistances": [],
  "damage_immunities": [],
  "condition_immunities": [],
  "senses": {
    "passive_perception": 12,
    "darkvision": "60 ft."
  },
  "languages": "Common",
  "challenge_rating": 4,
  "proficiency_bonus": 2,
  "xp": 1100,
  "url": "/api/2014/monsters/test-monster"
}


### GET UPDATED MONSTER (solo X-API-Token)
GET {{host}}/monsters/test-monster
Content-Type: application/json
X-API-Token: {{api_token_hash}}


### DELETE MONSTER (requiere X-API-Token + Authorization)
DELETE {{host}}/monsters/test-monster
Content-Type: application/json
X-API-Token: {{api_token_hash}}
Authorization: Bearer {{login.response.body.$.access_token}}


### VERIFY MONSTER DELETED (should return 404)
GET {{host}}/monsters/test-monster
Content-Type: application/json
X-API-Token: {{api_token_hash}}
